### ISSUE TITLE
xcframework対応の要望

### ISSUE THREAD

**Issue by ikesyo** [glossom-dev/GlossomAds-iOS#4]
SDK配布にxcframeworkが使われていないため、Appleシリコン搭載のMac上のiOSシミュレーター（arm64）向けにアプリをビルドすることができません。

参考: https://onesignal.com/blog/xcframeworks-guide/

**Comment by masha76** [comment]
ご意見ありがとうございます。
AdCorsaはクローズ予定ですので、xcframework対応予定はありません。
